### ISSUE TITLE
Category names should be moderated

### ISSUE THREAD

**Issue by ritmatter** [krazemon/repcoin#577]

**Comment by ritmatter** [comment]
1) User puts in category input
2) User receives message saying that the category is under review
3) Email is sent to admin (repcoin address). Email contains link to accept or link to deny.

If deny: send notification to person who's category was denied. For now this can be standardized.
If accept: send notification to person who's category was accepted. For now this can be standardized.

Optional: Send personal email from the Repcoin founders to the user

**Comment by krazemon** [comment]
This is exactly how I was imagining it, except I'd add a 4) Category added to user's expert or investor categories automatically.
