### ISSUE TITLE
The Big Data Migration

### ISSUE THREAD

**Issue by ritmatter** [krazemon/repcoin#600]
1) Blow up categories that are ridiculous
2) Blow up everyone's investments
3) Reset everyone's reps to some higher number (say, 30)
4) Delete all transactions involving categories that have been deleted

Question: What should we do about the transactions for existing categories that are no longer valid? We don't want an entirely empty feed, but mocked data also kinda sucks. This can be debated over the course of the day.

**Comment by krazemon** [comment]
Let's delete the transactions and then we can recreate or fake new ones somehow. ACTUALLY, even better, let's delete them but also mongoexport them into a json file.

**Comment by ritmatter** [comment]
Wait if we want fake transactions is it worth it to delete the actual ones? I don't see what the difference is except that the fake ones will be very time consuming to create and less real-seeming.
