### ISSUE TITLE
Repcoin needs to allow invitations over email

### ISSUE THREAD

**Issue by ritmatter** [krazemon/repcoin#646]

**Comment by timofei7** [comment]
I think it'd be important for any invitations to give extra reps to the inviter when the invitee creates an account and for the invitee also.  So if you generate a signup code/url for me to send people then I would be more likely to use it as there is an incentive. Also people are more likely to sign up when there are "extra" incentives both to them and to their friends.   But yes you'd have to track the code.  But its just one code so my user would need an invite code field and then when people sign up you'd check the invite code and give reps to the user who has that code.    I saw the FB invite but I'm holding off on using it till I can get reps for my invites!! :-)

**Comment by krazemon** [comment]
Closing this.
