### ISSUE TITLE
Delete Expert Category experiences scale problems

### ISSUE THREAD

**Issue by ritmatter** [krazemon/repcoin#708]
Deleting too many expert categories at once (done by Nook), creates the following series of errors:

Feb 25 06:33:51 quiet-spire-2804 app/web.1:  error: utils.saveAll: error saving doc: VersionError: No matching document found. 
Feb 25 06:33:51 quiet-spire-2804 app/web.1:  error: utils.updateInvestorPercentilesAndDividends: error saving investors: %s 
Feb 25 06:33:51 quiet-spire-2804 app/web.1:  error: Error updating percentiles: VersionError: No matching document found. 
Feb 25 06:33:54 quiet-spire-2804 app/web.1:  error: utils.saveAll: error saving doc: VersionError: No matching document found. 
Feb 25 06:33:54 quiet-spire-2804 app/web.1:  error: utils.updateInvestorPercentilesAndDividends: error saving investors: %s 
Feb 25 06:33:54 quiet-spire-2804 app/web.1:  error: Error updating percentiles: VersionError: No matching document found. 
Feb 25 06:33:55 quiet-spire-2804 app/web.1:  error: utils.saveAll: error saving doc: VersionError: No matching document found. 
Feb 25 06:33:56 quiet-spire-2804 app/web.1:  error: utils.updateInvestorPercentilesAndDividends: error saving investors: %s 
Feb 25 06:33:56 quiet-spire-2804 app/web.1:  error: Error updating percentiles: VersionError: No matching document found. 
Feb 25 06:33:57 quiet-spire-2804 app/web.1:  error: utils.saveAll: error saving doc: VersionError: No matching document found. 
Feb 25 06:33:57 quiet-spire-2804 app/web.1:  error: utils.updateInvestorPercentilesAndDividends: error saving investors: %s 
Feb 25 06:33:57 quiet-spire-2804 app/web.1:  error: Error updating percentiles: VersionError: No matching document found. 
Feb 25 06:35:50 quiet-spire-2804 app/web.1:  error: utils.saveAll: error saving doc: VersionError: No matching document found. 
Feb 25 06:35:50 quiet-spire-2804 app/web.1:  error: utils.updateInvestorPercentilesAndDividends: error saving investors: %s 
Feb 25 06:35:50 quiet-spire-2804 app/web.1:  error: Error updating percentiles: VersionError: No matching document found. 

This is happening because we are trying to modify documents that have been saved already. The second delete expert category event is attempting to fetch all of the experts and investors in that category and reset their percentiles. The problem is that those experts are already been modified.

You can read more about this here: http://stackoverflow.com/questions/17499089/versionerror-no-matching-document-found-error-on-node-js-mongoose

This is a big issue for us. Our system does not scale. It seems like there are some solutions, all of which are not easy:

1) Always include a callback in save() calls. This could be done by modifying our saveAll(), but it may be messy and slow. It probably will also not be as easy as this sounds.
2) Create a queueing system. This would probably involve using some kind of locking mechanism from an outside party. This also sounds large and difficult.

I think it's important to note that while right now, this issue is specific to a use case that does not happen much, it will probably occur more as more transactions happen. Many of our routes update the percentiles in batch.

3) I also want to put a third solution down here: Update the percentiles every 30 minutes as a job. This job has not been written yet because when I tried, I also encountered all of the concurrency problems. A job would mean the percentiles are not immediate, but there would not be a long queueing time.

4) And the last, possibly easiest, solution. Paying for another Heroku dyno would in theory increase our speed a ton, at least enough that these problems might occur significantly less.

**Comment by krazemon** [comment]
I believe this is completed also?

**Comment by ritmatter** [comment]
Should be!
